# Generated by Django 2.2.6 on 2019-11-03 02:10

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='col',
            field=models.IntegerField(validators=[game.models.validate_col_range]),
        ),
        migrations.AlterField(
            model_name='player',
            name='row',
            field=models.IntegerField(validators=[game.models.validate_row_range]),
        ),
        migrations.AlterField(
            model_name='player',
            name='tag',
            field=models.CharField(max_length=1, validators=[game.models.validate_unique_tag]),
        ),
    ]
