# Generated by Django 2.2.6 on 2019-11-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191103_0210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Board',
        ),
    ]
