# Generated by Django 2.2.6 on 2019-11-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191104_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cols',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='rows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
